# dataのロード方法をV2(eeg_idでまとめずに全データを使用する方式)に変更
gpu: 0
seed: 42
height: 128 # モデルに入力する画像サイズ
width: 256

logger:
  project: kaggle_hms_2024
  runName: SED_effnetb0
  mode: online # "online" or "offline" or "debug"

datamodule:
  batch_size: 32
  num_workers: 10
  pin_memory: False
  use_sampler: False

checkpoint:
  save_weights_only: True
  save_top_k: 1
  save_last: False
  every_n_epochs: &every_n_epochs 1
  monitor: val_metric_kldiv
  mode: min

train:
  epoch: &epoch 10
  # step: 300
  n_accumulations: 1
  val_check_interval: 1.0
  check_val_every_n_epoch: *every_n_epochs
  amp: True
  gradient_clip_val: 0.0
  deterministic: False

dataset:
  csv_path: ../hms-harmful-brain-activity-classification/train_fold_irr_mark.csv
  spec_dir_path: ../hms-harmful-brain-activity-classification/train_spectrograms
  eeg_dir_path: ../hms-harmful-brain-activity-classification/train_eegs
  type_of_data: ["kaggle_spec", "eeg_spec"]
  eeg_spec_dir_path: ../hms-harmful-brain-activity-classification/EEG_Spectrograms/ver2
  # eeg_spec_dir_path: ../hms-harmful-brain-activity-classification/EEG_Spectrograms/ver2_db8
  # eeg_spec_dir_path: ../hms-harmful-brain-activity-classification/EEG_Spectrograms/ver2_haar
  # eeg_spec_dir_path: ../hms-harmful-brain-activity-classification/EEG_Spectrograms/ver3_filtered
  fold: 0
  k_fold: 4
  normalize_method: all # "all" or "each"
  vote_min_thresh: 0
  eeg_nan_ratio_thresh: 1.0
  spec_nan_ratio_thresh: 1.0

transforms:
  train:
    - type: HorizontalFlip
      params:
        p: 0.5
    - type: CoarseDropout # 時間方向のSpecAug
      params:
        p: 0.2
        min_holes: 1
        max_holes: 8
        max_height: 128
        min_width: 1
        max_width: 10
    - type: CoarseDropout # 周波数方向のSpecAug
      params:
        p: 0.2
        min_holes: 1
        max_holes: 8
        min_height: 1
        max_height: 5
        max_width: 256
  val:

module:
  last_n_epoch_refined_augment: -1
  mix_augmentation: ["mixup"] #["mixup", "alphamix"]
  p_mix_augmentation: 0.2

model:
  name: HMSSEDModel
  args:
    # backbone: resnet18d
    # backbone: resnet34d
    backbone: tf_efficientnet_b0_ns
    # backbone: tf_efficientnetv2_b0
    # backbone: seresnext26ts
    # backbone: convnext_small_384_in22ft1k
    # backbone: swinv2_tiny_window8_256 # 256*256, b=32
    # backbone: swinv2_base_window12to24_192to384_22kft1k # 384*384, b=16
    num_classes: 6
    in_channels: 1 #1 #4
    pretrained: True
    channel_flatting: True
    sed_model: tf_efficientnet_b0_ns
  load_checkpoint:
  freeze_start:
    target_epoch:
    unfreeze_params:

loss:
  name: HMSSEDLoss
  args:
    loss_weight: [1.0, 0.5, 0.05] # main_kldiv, kspec_kldiv, kspec_bce

optimizer:
  name: AdamW
  args:
    lr: 1.e-3
    weight_decay: 1.e-2 # 1e-2
  # name: SGD
  # args:
  #   lr: 1.e-2
  #   weight_decay: 1.e-4
  #   momentum: 0.9
  #   nesterov: True
  scheduler:
    name: CosineAnnealingLR
    args:
      eta_min: 1.e-6
      last_epoch: -1
      T_max: *epoch
    lr_dict_param:
      interval: epoch
      # interval: step
